//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17626.
// 
#pragma warning disable 1591

namespace WebApplication1.jdcmobile {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PageStoreServiceSoap", Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class PageStoreService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDefaultPageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindPagesWithCriteriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLanguageBranchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateLanguageBranchOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteLanguageBranchOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveToWastebasketOperationCompleted;
        
        private System.Threading.SendOrPostCallback CopyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PageStoreService() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_jdcmobile_PageStoreService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDefaultPageDataCompletedEventHandler GetDefaultPageDataCompleted;
        
        /// <remarks/>
        public event GetChildrenCompletedEventHandler GetChildrenCompleted;
        
        /// <remarks/>
        public event GetPageCompletedEventHandler GetPageCompleted;
        
        /// <remarks/>
        public event FindPagesWithCriteriaCompletedEventHandler FindPagesWithCriteriaCompleted;
        
        /// <remarks/>
        public event GetLanguageBranchesCompletedEventHandler GetLanguageBranchesCompleted;
        
        /// <remarks/>
        public event CreateLanguageBranchCompletedEventHandler CreateLanguageBranchCompleted;
        
        /// <remarks/>
        public event DeleteLanguageBranchCompletedEventHandler DeleteLanguageBranchCompleted;
        
        /// <remarks/>
        public event DeleteVersionCompletedEventHandler DeleteVersionCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event DeleteChildrenCompletedEventHandler DeleteChildrenCompleted;
        
        /// <remarks/>
        public event MoveCompletedEventHandler MoveCompleted;
        
        /// <remarks/>
        public event MoveToWastebasketCompletedEventHandler MoveToWastebasketCompleted;
        
        /// <remarks/>
        public event CopyCompletedEventHandler CopyCompleted;
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/GetDefaultPageData", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawPage GetDefaultPageData(PageReference parentPageLink, int pageTypeID, LanguageSelector selector, AccessLevel access) {
            object[] results = this.Invoke("GetDefaultPageData", new object[] {
                        parentPageLink,
                        pageTypeID,
                        selector,
                        access});
            return ((RawPage)(results[0]));
        }
        
        /// <remarks/>
        public void GetDefaultPageDataAsync(PageReference parentPageLink, int pageTypeID, LanguageSelector selector, AccessLevel access) {
            this.GetDefaultPageDataAsync(parentPageLink, pageTypeID, selector, access, null);
        }
        
        /// <remarks/>
        public void GetDefaultPageDataAsync(PageReference parentPageLink, int pageTypeID, LanguageSelector selector, AccessLevel access, object userState) {
            if ((this.GetDefaultPageDataOperationCompleted == null)) {
                this.GetDefaultPageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultPageDataOperationCompleted);
            }
            this.InvokeAsync("GetDefaultPageData", new object[] {
                        parentPageLink,
                        pageTypeID,
                        selector,
                        access}, this.GetDefaultPageDataOperationCompleted, userState);
        }
        
        private void OnGetDefaultPageDataOperationCompleted(object arg) {
            if ((this.GetDefaultPageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultPageDataCompleted(this, new GetDefaultPageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/GetChildren", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawPage[] GetChildren(PageReference pageLink, LanguageSelector selector, int startIndex, int maxRows) {
            object[] results = this.Invoke("GetChildren", new object[] {
                        pageLink,
                        selector,
                        startIndex,
                        maxRows});
            return ((RawPage[])(results[0]));
        }
        
        /// <remarks/>
        public void GetChildrenAsync(PageReference pageLink, LanguageSelector selector, int startIndex, int maxRows) {
            this.GetChildrenAsync(pageLink, selector, startIndex, maxRows, null);
        }
        
        /// <remarks/>
        public void GetChildrenAsync(PageReference pageLink, LanguageSelector selector, int startIndex, int maxRows, object userState) {
            if ((this.GetChildrenOperationCompleted == null)) {
                this.GetChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChildrenOperationCompleted);
            }
            this.InvokeAsync("GetChildren", new object[] {
                        pageLink,
                        selector,
                        startIndex,
                        maxRows}, this.GetChildrenOperationCompleted, userState);
        }
        
        private void OnGetChildrenOperationCompleted(object arg) {
            if ((this.GetChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChildrenCompleted(this, new GetChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/GetPage", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawPage GetPage(PageReference pageLink, LanguageSelector selector, AccessLevel access) {
            object[] results = this.Invoke("GetPage", new object[] {
                        pageLink,
                        selector,
                        access});
            return ((RawPage)(results[0]));
        }
        
        /// <remarks/>
        public void GetPageAsync(PageReference pageLink, LanguageSelector selector, AccessLevel access) {
            this.GetPageAsync(pageLink, selector, access, null);
        }
        
        /// <remarks/>
        public void GetPageAsync(PageReference pageLink, LanguageSelector selector, AccessLevel access, object userState) {
            if ((this.GetPageOperationCompleted == null)) {
                this.GetPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPageOperationCompleted);
            }
            this.InvokeAsync("GetPage", new object[] {
                        pageLink,
                        selector,
                        access}, this.GetPageOperationCompleted, userState);
        }
        
        private void OnGetPageOperationCompleted(object arg) {
            if ((this.GetPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPageCompleted(this, new GetPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/FindPagesWithCriteria", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawPage[] FindPagesWithCriteria(PageReference pageLink, PropertyCriteria[] criterias, string languageBranch, LanguageSelector selector, AccessLevel requiredAccess) {
            object[] results = this.Invoke("FindPagesWithCriteria", new object[] {
                        pageLink,
                        criterias,
                        languageBranch,
                        selector,
                        requiredAccess});
            return ((RawPage[])(results[0]));
        }
        
        /// <remarks/>
        public void FindPagesWithCriteriaAsync(PageReference pageLink, PropertyCriteria[] criterias, string languageBranch, LanguageSelector selector, AccessLevel requiredAccess) {
            this.FindPagesWithCriteriaAsync(pageLink, criterias, languageBranch, selector, requiredAccess, null);
        }
        
        /// <remarks/>
        public void FindPagesWithCriteriaAsync(PageReference pageLink, PropertyCriteria[] criterias, string languageBranch, LanguageSelector selector, AccessLevel requiredAccess, object userState) {
            if ((this.FindPagesWithCriteriaOperationCompleted == null)) {
                this.FindPagesWithCriteriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindPagesWithCriteriaOperationCompleted);
            }
            this.InvokeAsync("FindPagesWithCriteria", new object[] {
                        pageLink,
                        criterias,
                        languageBranch,
                        selector,
                        requiredAccess}, this.FindPagesWithCriteriaOperationCompleted, userState);
        }
        
        private void OnFindPagesWithCriteriaOperationCompleted(object arg) {
            if ((this.FindPagesWithCriteriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindPagesWithCriteriaCompleted(this, new FindPagesWithCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/GetLanguageBranches", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawPage[] GetLanguageBranches(PageReference pageLink, AccessLevel access) {
            object[] results = this.Invoke("GetLanguageBranches", new object[] {
                        pageLink,
                        access});
            return ((RawPage[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLanguageBranchesAsync(PageReference pageLink, AccessLevel access) {
            this.GetLanguageBranchesAsync(pageLink, access, null);
        }
        
        /// <remarks/>
        public void GetLanguageBranchesAsync(PageReference pageLink, AccessLevel access, object userState) {
            if ((this.GetLanguageBranchesOperationCompleted == null)) {
                this.GetLanguageBranchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLanguageBranchesOperationCompleted);
            }
            this.InvokeAsync("GetLanguageBranches", new object[] {
                        pageLink,
                        access}, this.GetLanguageBranchesOperationCompleted, userState);
        }
        
        private void OnGetLanguageBranchesOperationCompleted(object arg) {
            if ((this.GetLanguageBranchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLanguageBranchesCompleted(this, new GetLanguageBranchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/CreateLanguageBranch", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawPage CreateLanguageBranch(PageReference pageLink, LanguageSelector selector, AccessLevel access) {
            object[] results = this.Invoke("CreateLanguageBranch", new object[] {
                        pageLink,
                        selector,
                        access});
            return ((RawPage)(results[0]));
        }
        
        /// <remarks/>
        public void CreateLanguageBranchAsync(PageReference pageLink, LanguageSelector selector, AccessLevel access) {
            this.CreateLanguageBranchAsync(pageLink, selector, access, null);
        }
        
        /// <remarks/>
        public void CreateLanguageBranchAsync(PageReference pageLink, LanguageSelector selector, AccessLevel access, object userState) {
            if ((this.CreateLanguageBranchOperationCompleted == null)) {
                this.CreateLanguageBranchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateLanguageBranchOperationCompleted);
            }
            this.InvokeAsync("CreateLanguageBranch", new object[] {
                        pageLink,
                        selector,
                        access}, this.CreateLanguageBranchOperationCompleted, userState);
        }
        
        private void OnCreateLanguageBranchOperationCompleted(object arg) {
            if ((this.CreateLanguageBranchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateLanguageBranchCompleted(this, new CreateLanguageBranchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/DeleteLanguageBranch", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteLanguageBranch(PageReference pageLink, string languageBranch, AccessLevel access) {
            this.Invoke("DeleteLanguageBranch", new object[] {
                        pageLink,
                        languageBranch,
                        access});
        }
        
        /// <remarks/>
        public void DeleteLanguageBranchAsync(PageReference pageLink, string languageBranch, AccessLevel access) {
            this.DeleteLanguageBranchAsync(pageLink, languageBranch, access, null);
        }
        
        /// <remarks/>
        public void DeleteLanguageBranchAsync(PageReference pageLink, string languageBranch, AccessLevel access, object userState) {
            if ((this.DeleteLanguageBranchOperationCompleted == null)) {
                this.DeleteLanguageBranchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteLanguageBranchOperationCompleted);
            }
            this.InvokeAsync("DeleteLanguageBranch", new object[] {
                        pageLink,
                        languageBranch,
                        access}, this.DeleteLanguageBranchOperationCompleted, userState);
        }
        
        private void OnDeleteLanguageBranchOperationCompleted(object arg) {
            if ((this.DeleteLanguageBranchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteLanguageBranchCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/DeleteVersion", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteVersion(PageReference pageLink, AccessLevel access) {
            this.Invoke("DeleteVersion", new object[] {
                        pageLink,
                        access});
        }
        
        /// <remarks/>
        public void DeleteVersionAsync(PageReference pageLink, AccessLevel access) {
            this.DeleteVersionAsync(pageLink, access, null);
        }
        
        /// <remarks/>
        public void DeleteVersionAsync(PageReference pageLink, AccessLevel access, object userState) {
            if ((this.DeleteVersionOperationCompleted == null)) {
                this.DeleteVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteVersionOperationCompleted);
            }
            this.InvokeAsync("DeleteVersion", new object[] {
                        pageLink,
                        access}, this.DeleteVersionOperationCompleted, userState);
        }
        
        private void OnDeleteVersionOperationCompleted(object arg) {
            if ((this.DeleteVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteVersionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/Delete", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Delete(PageReference pageLink, bool forceDelete, AccessLevel access) {
            this.Invoke("Delete", new object[] {
                        pageLink,
                        forceDelete,
                        access});
        }
        
        /// <remarks/>
        public void DeleteAsync(PageReference pageLink, bool forceDelete, AccessLevel access) {
            this.DeleteAsync(pageLink, forceDelete, access, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(PageReference pageLink, bool forceDelete, AccessLevel access, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        pageLink,
                        forceDelete,
                        access}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/DeleteChildren", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteChildren(PageReference pageLink, bool forceDelete, AccessLevel access) {
            this.Invoke("DeleteChildren", new object[] {
                        pageLink,
                        forceDelete,
                        access});
        }
        
        /// <remarks/>
        public void DeleteChildrenAsync(PageReference pageLink, bool forceDelete, AccessLevel access) {
            this.DeleteChildrenAsync(pageLink, forceDelete, access, null);
        }
        
        /// <remarks/>
        public void DeleteChildrenAsync(PageReference pageLink, bool forceDelete, AccessLevel access, object userState) {
            if ((this.DeleteChildrenOperationCompleted == null)) {
                this.DeleteChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteChildrenOperationCompleted);
            }
            this.InvokeAsync("DeleteChildren", new object[] {
                        pageLink,
                        forceDelete,
                        access}, this.DeleteChildrenOperationCompleted, userState);
        }
        
        private void OnDeleteChildrenOperationCompleted(object arg) {
            if ((this.DeleteChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteChildrenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/Move", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Move(PageReference pageLink, PageReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess) {
            this.Invoke("Move", new object[] {
                        pageLink,
                        destinationLink,
                        requiredSourceAccess,
                        requiredDestinationAccess});
        }
        
        /// <remarks/>
        public void MoveAsync(PageReference pageLink, PageReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess) {
            this.MoveAsync(pageLink, destinationLink, requiredSourceAccess, requiredDestinationAccess, null);
        }
        
        /// <remarks/>
        public void MoveAsync(PageReference pageLink, PageReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess, object userState) {
            if ((this.MoveOperationCompleted == null)) {
                this.MoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveOperationCompleted);
            }
            this.InvokeAsync("Move", new object[] {
                        pageLink,
                        destinationLink,
                        requiredSourceAccess,
                        requiredDestinationAccess}, this.MoveOperationCompleted, userState);
        }
        
        private void OnMoveOperationCompleted(object arg) {
            if ((this.MoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/MoveToWastebasket", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MoveToWastebasket(PageReference pageLink) {
            this.Invoke("MoveToWastebasket", new object[] {
                        pageLink});
        }
        
        /// <remarks/>
        public void MoveToWastebasketAsync(PageReference pageLink) {
            this.MoveToWastebasketAsync(pageLink, null);
        }
        
        /// <remarks/>
        public void MoveToWastebasketAsync(PageReference pageLink, object userState) {
            if ((this.MoveToWastebasketOperationCompleted == null)) {
                this.MoveToWastebasketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveToWastebasketOperationCompleted);
            }
            this.InvokeAsync("MoveToWastebasket", new object[] {
                        pageLink}, this.MoveToWastebasketOperationCompleted, userState);
        }
        
        private void OnMoveToWastebasketOperationCompleted(object arg) {
            if ((this.MoveToWastebasketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveToWastebasketCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/Copy", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PageReference Copy(PageReference pageLink, PageReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess, bool publishOnDestination, bool allowThreading) {
            object[] results = this.Invoke("Copy", new object[] {
                        pageLink,
                        destinationLink,
                        requiredSourceAccess,
                        requiredDestinationAccess,
                        publishOnDestination,
                        allowThreading});
            return ((PageReference)(results[0]));
        }
        
        /// <remarks/>
        public void CopyAsync(PageReference pageLink, PageReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess, bool publishOnDestination, bool allowThreading) {
            this.CopyAsync(pageLink, destinationLink, requiredSourceAccess, requiredDestinationAccess, publishOnDestination, allowThreading, null);
        }
        
        /// <remarks/>
        public void CopyAsync(PageReference pageLink, PageReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess, bool publishOnDestination, bool allowThreading, object userState) {
            if ((this.CopyOperationCompleted == null)) {
                this.CopyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyOperationCompleted);
            }
            this.InvokeAsync("Copy", new object[] {
                        pageLink,
                        destinationLink,
                        requiredSourceAccess,
                        requiredDestinationAccess,
                        publishOnDestination,
                        allowThreading}, this.CopyOperationCompleted, userState);
        }
        
        private void OnCopyOperationCompleted(object arg) {
            if ((this.CopyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyCompleted(this, new CopyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/Save", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PageReference Save(RawPage page, SaveAction action, AccessLevel access) {
            object[] results = this.Invoke("Save", new object[] {
                        page,
                        action,
                        access});
            return ((PageReference)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAsync(RawPage page, SaveAction action, AccessLevel access) {
            this.SaveAsync(page, action, access, null);
        }
        
        /// <remarks/>
        public void SaveAsync(RawPage page, SaveAction action, AccessLevel access, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        page,
                        action,
                        access}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.episerver.com/WebServices/v5/Ping", RequestNamespace="http://schemas.episerver.com/WebServices/v5/", ResponseNamespace="http://schemas.episerver.com/WebServices/v5/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class PageReference {
        
        private int idField;
        
        private int workIDField;
        
        private string remoteSiteField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int WorkID {
            get {
                return this.workIDField;
            }
            set {
                this.workIDField = value;
            }
        }
        
        /// <remarks/>
        public string RemoteSite {
            get {
                return this.remoteSiteField;
            }
            set {
                this.remoteSiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class PropertyCriteria {
        
        private string nameField;
        
        private string valueField;
        
        private PropertyDataType typeField;
        
        private CompareCondition conditionField;
        
        private bool isNullField;
        
        private bool requiredField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public PropertyDataType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public CompareCondition Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNull {
            get {
                return this.isNullField;
            }
            set {
                this.isNullField = value;
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public enum PropertyDataType {
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        FloatNumber,
        
        /// <remarks/>
        PageType,
        
        /// <remarks/>
        PageReference,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        LongString,
        
        /// <remarks/>
        Category,
        
        /// <remarks/>
        LinkCollection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public enum CompareCondition {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        GreaterThan,
        
        /// <remarks/>
        LessThan,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        StartsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        Contained,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class RawPageObject {
        
        private System.Guid objectExternalIdField;
        
        private string storeNameField;
        
        private string nameField;
        
        private OwnerOption ownerField;
        
        /// <remarks/>
        public System.Guid ObjectExternalId {
            get {
                return this.objectExternalIdField;
            }
            set {
                this.objectExternalIdField = value;
            }
        }
        
        /// <remarks/>
        public string StoreName {
            get {
                return this.storeNameField;
            }
            set {
                this.storeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public OwnerOption Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public enum OwnerOption {
        
        /// <remarks/>
        Page,
        
        /// <remarks/>
        PageLanguageBranch,
        
        /// <remarks/>
        PageVersion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class RawACE {
        
        private System.Nullable<SecurityEntityType> entityTypeField;
        
        private int sIDField;
        
        private AccessLevel accessField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<SecurityEntityType> EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
            }
        }
        
        /// <remarks/>
        public AccessLevel Access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public enum SecurityEntityType {
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Role,
        
        /// <remarks/>
        VisitorGroup,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public enum AccessLevel {
        
        /// <remarks/>
        NoAccess = 1,
        
        /// <remarks/>
        Read = 2,
        
        /// <remarks/>
        Create = 4,
        
        /// <remarks/>
        Edit = 8,
        
        /// <remarks/>
        Delete = 16,
        
        /// <remarks/>
        Publish = 32,
        
        /// <remarks/>
        Administer = 64,
        
        /// <remarks/>
        FullAccess = 128,
        
        /// <remarks/>
        Undefined = 256,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class RawNameAndXml {
        
        private string nameField;
        
        private string xmlField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class RawProperty {
        
        private int pageDefinitionIDField;
        
        private int ownerTabField;
        
        private bool isModifiedField;
        
        private bool isNullField;
        
        private bool isRequiredField;
        
        private bool isPropertyDataField;
        
        private bool isDynamicPropertyField;
        
        private bool isLanguageSpecificField;
        
        private PropertyDataType typeField;
        
        private string nameField;
        
        private string displayNameField;
        
        private string descriptionField;
        
        private string languageKeyField;
        
        private string typeNameField;
        
        private string assemblyNameField;
        
        private string valueField;
        
        private RawNameAndXml[] customDataField;
        
        /// <remarks/>
        public int PageDefinitionID {
            get {
                return this.pageDefinitionIDField;
            }
            set {
                this.pageDefinitionIDField = value;
            }
        }
        
        /// <remarks/>
        public int OwnerTab {
            get {
                return this.ownerTabField;
            }
            set {
                this.ownerTabField = value;
            }
        }
        
        /// <remarks/>
        public bool IsModified {
            get {
                return this.isModifiedField;
            }
            set {
                this.isModifiedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNull {
            get {
                return this.isNullField;
            }
            set {
                this.isNullField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPropertyData {
            get {
                return this.isPropertyDataField;
            }
            set {
                this.isPropertyDataField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDynamicProperty {
            get {
                return this.isDynamicPropertyField;
            }
            set {
                this.isDynamicPropertyField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLanguageSpecific {
            get {
                return this.isLanguageSpecificField;
            }
            set {
                this.isLanguageSpecificField = value;
            }
        }
        
        /// <remarks/>
        public PropertyDataType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageKey {
            get {
                return this.languageKeyField;
            }
            set {
                this.languageKeyField = value;
            }
        }
        
        /// <remarks/>
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        public string AssemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public RawNameAndXml[] CustomData {
            get {
                return this.customDataField;
            }
            set {
                this.customDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class RawPage {
        
        private RawProperty[] propertyField;
        
        private RawACE[] aCLField;
        
        private RawPageObject[] pageObjectsField;
        
        /// <remarks/>
        public RawProperty[] Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public RawACE[] ACL {
            get {
                return this.aCLField;
            }
            set {
                this.aCLField = value;
            }
        }
        
        /// <remarks/>
        public RawPageObject[] PageObjects {
            get {
                return this.pageObjectsField;
            }
            set {
                this.pageObjectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public partial class LanguageSelector {
        
        private string languageBranchField;
        
        /// <remarks/>
        public string LanguageBranch {
            get {
                return this.languageBranchField;
            }
            set {
                this.languageBranchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.episerver.com/WebServices/v5/")]
    public enum SaveAction {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Save,
        
        /// <remarks/>
        CheckIn,
        
        /// <remarks/>
        Publish,
        
        /// <remarks/>
        Reject,
        
        /// <remarks/>
        ForceNewVersion,
        
        /// <remarks/>
        ForceCurrentVersion,
        
        /// <remarks/>
        ActionMask,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void GetDefaultPageDataCompletedEventHandler(object sender, GetDefaultPageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultPageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDefaultPageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void GetChildrenCompletedEventHandler(object sender, GetChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawPage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawPage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void GetPageCompletedEventHandler(object sender, GetPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void FindPagesWithCriteriaCompletedEventHandler(object sender, FindPagesWithCriteriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindPagesWithCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindPagesWithCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawPage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawPage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void GetLanguageBranchesCompletedEventHandler(object sender, GetLanguageBranchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLanguageBranchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLanguageBranchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawPage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawPage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void CreateLanguageBranchCompletedEventHandler(object sender, CreateLanguageBranchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateLanguageBranchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateLanguageBranchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void DeleteLanguageBranchCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void DeleteVersionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void DeleteChildrenCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void MoveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void MoveToWastebasketCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void CopyCompletedEventHandler(object sender, CopyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CopyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageReference Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageReference)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageReference Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageReference)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17626")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591