using System.Collections.ObjectModel;

namespace Utility
{
    static class Country
    {
        /// <summary>
        /// Gets the countries as defined in ISO 3166-1 aplha 2.
        /// </summary>
        /// <returns></returns>
        public static Collection<NameValuePair> List()
        {
            Collection<NameValuePair> countries = new Collection<NameValuePair>();

            // This is the ISO 3166-1 aplha 2 list
            countries.Add(new NameValuePair {Name = "Afghanistan", Value = "AF"});
            countries.Add(new NameValuePair {Name = "Aland Islands Åland Islands", Value = "AX"});
            countries.Add(new NameValuePair {Name = "Albania", Value = "AL"});
            countries.Add(new NameValuePair {Name = "Algeria", Value = "DZ"});
            countries.Add(new NameValuePair {Name = "American Samoa", Value = "AS"});
            countries.Add(new NameValuePair {Name = "Andorra", Value = "AD"});
            countries.Add(new NameValuePair {Name = "Angola", Value = "AO"});
            countries.Add(new NameValuePair {Name = "Anguilla", Value = "AI"});
            countries.Add(new NameValuePair {Name = "Antarctica", Value = "AQ"});
            countries.Add(new NameValuePair {Name = "Antigua and Barbuda", Value = "AG"});
            countries.Add(new NameValuePair {Name = "Argentina", Value = "AR"});
            countries.Add(new NameValuePair {Name = "Armenia", Value = "AM"});
            countries.Add(new NameValuePair {Name = "Aruba", Value = "AW"});
            countries.Add(new NameValuePair {Name = "Australia", Value = "AU"});
            countries.Add(new NameValuePair {Name = "Austria", Value = "AT"});
            countries.Add(new NameValuePair {Name = "Azerbaijan", Value = "AZ"});
            countries.Add(new NameValuePair {Name = "Bahamas", Value = "BS"});
            countries.Add(new NameValuePair {Name = "Bahrain", Value = "BH"});
            countries.Add(new NameValuePair {Name = "Bangladesh", Value = "BD"});
            countries.Add(new NameValuePair {Name = "Barbados", Value = "BB"});
            countries.Add(new NameValuePair {Name = "Belarus", Value = "BY"});
            countries.Add(new NameValuePair {Name = "Belgium", Value = "BE"});
            countries.Add(new NameValuePair {Name = "Belize", Value = "BZ"});
            countries.Add(new NameValuePair {Name = "Benin", Value = "BJ"});
            countries.Add(new NameValuePair {Name = "Bermuda", Value = "BM"});
            countries.Add(new NameValuePair {Name = "Bhutan", Value = "BT"});
            countries.Add(new NameValuePair {Name = "Bolivia", Value = "BO"});
            countries.Add(new NameValuePair {Name = "Bosnia and Herzegovina", Value = "BA"});
            countries.Add(new NameValuePair {Name = "Botswana", Value = "BW"});
            countries.Add(new NameValuePair {Name = "Bouvet Island", Value = "BV"});
            countries.Add(new NameValuePair {Name = "Brazil", Value = "BR"});
            countries.Add(new NameValuePair {Name = "British Indian Ocean Territory", Value = "IO"});
            countries.Add(new NameValuePair {Name = "Brunei Darussalam", Value = "BN"});
            countries.Add(new NameValuePair {Name = "Bulgaria", Value = "BG"});
            countries.Add(new NameValuePair {Name = "Burkina Faso", Value = "BF"});
            countries.Add(new NameValuePair {Name = "Burundi", Value = "BI"});
            countries.Add(new NameValuePair {Name = "Cambodia", Value = "KH"});
            countries.Add(new NameValuePair {Name = "Cameroon", Value = "CM"});
            countries.Add(new NameValuePair {Name = "Canada", Value = "CA"});
            countries.Add(new NameValuePair {Name = "Cape Verde", Value = "CV"});
            countries.Add(new NameValuePair {Name = "Cayman Islands", Value = "KY"});
            countries.Add(new NameValuePair {Name = "Central African Republic", Value = "CF"});
            countries.Add(new NameValuePair {Name = "Chad", Value = "TD"});
            countries.Add(new NameValuePair {Name = "Chile", Value = "CL"});
            countries.Add(new NameValuePair {Name = "China", Value = "CN"});
            countries.Add(new NameValuePair {Name = "Christmas Island", Value = "CX"});
            countries.Add(new NameValuePair {Name = "Cocos (Keeling) Islands", Value = "CC"});
            countries.Add(new NameValuePair {Name = "Colombia", Value = "CO"});
            countries.Add(new NameValuePair {Name = "Comoros", Value = "KM"});
            countries.Add(new NameValuePair {Name = "Congo", Value = "CG"});
            countries.Add(new NameValuePair {Name = "Congo, the Democratic Republic of the", Value = "CD"});
            countries.Add(new NameValuePair {Name = "Cook Islands", Value = "CK"});
            countries.Add(new NameValuePair {Name = "Costa Rica", Value = "CR"});
            countries.Add(new NameValuePair {Name = "Cote d'Ivoire Côte d'Ivoire", Value = "CI"});
            countries.Add(new NameValuePair {Name = "Croatia", Value = "HR"});
            countries.Add(new NameValuePair {Name = "Cuba", Value = "CU"});
            countries.Add(new NameValuePair {Name = "Cyprus", Value = "CY"});
            countries.Add(new NameValuePair {Name = "Czech Republic", Value = "CZ"});
            countries.Add(new NameValuePair {Name = "Denmark", Value = "DK"});
            countries.Add(new NameValuePair {Name = "Djibouti", Value = "DJ"});
            countries.Add(new NameValuePair {Name = "Dominica", Value = "DM"});
            countries.Add(new NameValuePair {Name = "Dominican Republic", Value = "DO"});
            countries.Add(new NameValuePair {Name = "Ecuador", Value = "EC"});
            countries.Add(new NameValuePair {Name = "Egypt", Value = "EG"});
            countries.Add(new NameValuePair {Name = "El Salvador", Value = "SV"});
            countries.Add(new NameValuePair {Name = "Equatorial Guinea", Value = "GQ"});
            countries.Add(new NameValuePair {Name = "Eritrea", Value = "ER"});
            countries.Add(new NameValuePair {Name = "Estonia", Value = "EE"});
            countries.Add(new NameValuePair {Name = "Ethiopia", Value = "ET"});
            countries.Add(new NameValuePair {Name = "Falkland Islands (Malvinas)", Value = "FK"});
            countries.Add(new NameValuePair {Name = "Faroe Islands", Value = "FO"});
            countries.Add(new NameValuePair {Name = "Fiji", Value = "FJ"});
            countries.Add(new NameValuePair {Name = "Finland", Value = "FI"});
            countries.Add(new NameValuePair {Name = "France", Value = "FR"});
            countries.Add(new NameValuePair {Name = "French Guiana", Value = "GF"});
            countries.Add(new NameValuePair {Name = "French Polynesia", Value = "PF"});
            countries.Add(new NameValuePair {Name = "French Southern Territories", Value = "TF"});
            countries.Add(new NameValuePair {Name = "Gabon", Value = "GA"});
            countries.Add(new NameValuePair {Name = "Gambia", Value = "GM"});
            countries.Add(new NameValuePair {Name = "Georgia", Value = "GE"});
            countries.Add(new NameValuePair {Name = "Germany", Value = "DE"});
            countries.Add(new NameValuePair {Name = "Ghana", Value = "GH"});
            countries.Add(new NameValuePair {Name = "Gibraltar", Value = "GI"});
            countries.Add(new NameValuePair {Name = "Greece", Value = "GR"});
            countries.Add(new NameValuePair {Name = "Greenland", Value = "GL"});
            countries.Add(new NameValuePair {Name = "Grenada", Value = "GD"});
            countries.Add(new NameValuePair {Name = "Guadeloupe", Value = "GP"});
            countries.Add(new NameValuePair {Name = "Guam", Value = "GU"});
            countries.Add(new NameValuePair {Name = "Guatemala", Value = "GT"});
            countries.Add(new NameValuePair {Name = "Guernsey", Value = "GG"});
            countries.Add(new NameValuePair {Name = "Guinea", Value = "GN"});
            countries.Add(new NameValuePair {Name = "Guinea-Bissau", Value = "GW"});
            countries.Add(new NameValuePair {Name = "Guyana", Value = "GY"});
            countries.Add(new NameValuePair {Name = "Haiti", Value = "HT"});
            countries.Add(new NameValuePair {Name = "Heard Island and McDonald Islands", Value = "HM"});
            countries.Add(new NameValuePair {Name = "Holy See (Vatican City State)", Value = "VA"});
            countries.Add(new NameValuePair {Name = "Honduras", Value = "HN"});
            countries.Add(new NameValuePair {Name = "Hong Kong", Value = "HK"});
            countries.Add(new NameValuePair {Name = "Hungary", Value = "HU"});
            countries.Add(new NameValuePair {Name = "Iceland", Value = "IS"});
            countries.Add(new NameValuePair {Name = "India", Value = "IN"});
            countries.Add(new NameValuePair {Name = "Indonesia", Value = "ID"});
            countries.Add(new NameValuePair {Name = "Iran, Islamic Republic of", Value = "IR"});
            countries.Add(new NameValuePair {Name = "Iraq", Value = "IQ"});
            countries.Add(new NameValuePair {Name = "Ireland", Value = "IE"});
            countries.Add(new NameValuePair {Name = "Isle of Man", Value = "IM"});
            countries.Add(new NameValuePair {Name = "Israel", Value = "IL"});
            countries.Add(new NameValuePair {Name = "Italy", Value = "IT"});
            countries.Add(new NameValuePair {Name = "Jamaica", Value = "JM"});
            countries.Add(new NameValuePair {Name = "Japan", Value = "JP"});
            countries.Add(new NameValuePair {Name = "Jersey", Value = "JE"});
            countries.Add(new NameValuePair {Name = "Jordan", Value = "JO"});
            countries.Add(new NameValuePair {Name = "Kazakhstan", Value = "KZ"});
            countries.Add(new NameValuePair {Name = "Kenya", Value = "KE"});
            countries.Add(new NameValuePair {Name = "Kiribati", Value = "KI"});
            countries.Add(new NameValuePair {Name = "Korea, Democratic People's Republic of", Value = "KP"});
            countries.Add(new NameValuePair {Name = "Korea, Republic of", Value = "KR"});
            countries.Add(new NameValuePair {Name = "Kuwait", Value = "KW"});
            countries.Add(new NameValuePair {Name = "Kyrgyzstan", Value = "KG"});
            countries.Add(new NameValuePair {Name = "Lao People's Democratic Republic", Value = "LA"});
            countries.Add(new NameValuePair {Name = "Latvia", Value = "LV"});
            countries.Add(new NameValuePair {Name = "Lebanon", Value = "LB"});
            countries.Add(new NameValuePair {Name = "Lesotho", Value = "LS"});
            countries.Add(new NameValuePair {Name = "Liberia", Value = "LR"});
            countries.Add(new NameValuePair {Name = "Libyan Arab Jamahiriya", Value = "LY"});
            countries.Add(new NameValuePair {Name = "Liechtenstein", Value = "LI"});
            countries.Add(new NameValuePair {Name = "Lithuania", Value = "LT"});
            countries.Add(new NameValuePair {Name = "Luxembourg", Value = "LU"});
            countries.Add(new NameValuePair {Name = "Macao", Value = "MO"});
            countries.Add(new NameValuePair {Name = "Macedonia, the former Yugoslav Republic of", Value = "MK"});
            countries.Add(new NameValuePair {Name = "Madagascar", Value = "MG"});
            countries.Add(new NameValuePair {Name = "Malawi", Value = "MW"});
            countries.Add(new NameValuePair {Name = "Malaysia", Value = "MY"});
            countries.Add(new NameValuePair {Name = "Maldives", Value = "MV"});
            countries.Add(new NameValuePair {Name = "Mali", Value = "ML"});
            countries.Add(new NameValuePair {Name = "Malta", Value = "MT"});
            countries.Add(new NameValuePair {Name = "Marshall Islands", Value = "MH"});
            countries.Add(new NameValuePair {Name = "Martinique", Value = "MQ"});
            countries.Add(new NameValuePair {Name = "Mauritania", Value = "MR"});
            countries.Add(new NameValuePair {Name = "Mauritius", Value = "MU"});
            countries.Add(new NameValuePair {Name = "Mayotte", Value = "YT"});
            countries.Add(new NameValuePair {Name = "Mexico", Value = "MX"});
            countries.Add(new NameValuePair {Name = "Micronesia, Federated States of", Value = "FM"});
            countries.Add(new NameValuePair {Name = "Moldova", Value = "MD"});
            countries.Add(new NameValuePair {Name = "Monaco", Value = "MC"});
            countries.Add(new NameValuePair {Name = "Mongolia", Value = "MN"});
            countries.Add(new NameValuePair {Name = "Montenegro", Value = "ME"});
            countries.Add(new NameValuePair {Name = "Montserrat", Value = "MS"});
            countries.Add(new NameValuePair {Name = "Morocco", Value = "MA"});
            countries.Add(new NameValuePair {Name = "Mozambique", Value = "MZ"});
            countries.Add(new NameValuePair {Name = "Myanmar", Value = "MM"});
            countries.Add(new NameValuePair {Name = "Namibia", Value = "NA"});
            countries.Add(new NameValuePair {Name = "Nauru", Value = "NR"});
            countries.Add(new NameValuePair {Name = "Nepal", Value = "NP"});
            countries.Add(new NameValuePair {Name = "Netherlands Antilles", Value = "AN"});
            countries.Add(new NameValuePair {Name = "Netherlands", Value = "NL"});
            countries.Add(new NameValuePair {Name = "New Caledonia", Value = "NC"});
            countries.Add(new NameValuePair {Name = "New Zealand", Value = "NZ"});
            countries.Add(new NameValuePair {Name = "Nicaragua", Value = "NI"});
            countries.Add(new NameValuePair {Name = "Niger", Value = "NE"});
            countries.Add(new NameValuePair {Name = "Nigeria", Value = "NG"});
            countries.Add(new NameValuePair {Name = "Niue", Value = "NU"});
            countries.Add(new NameValuePair {Name = "Norfolk Island", Value = "NF"});
            countries.Add(new NameValuePair {Name = "Northern Mariana Islands", Value = "MP"});
            countries.Add(new NameValuePair {Name = "Norway", Value = "NO"});
            countries.Add(new NameValuePair {Name = "Oman", Value = "OM"});
            countries.Add(new NameValuePair {Name = "Pakistan", Value = "PK"});
            countries.Add(new NameValuePair {Name = "Palau", Value = "PW"});
            countries.Add(new NameValuePair {Name = "Palestinian Territory, Occupied", Value = "PS"});
            countries.Add(new NameValuePair {Name = "Panama", Value = "PA"});
            countries.Add(new NameValuePair {Name = "Papua New Guinea", Value = "PG"});
            countries.Add(new NameValuePair {Name = "Paraguay", Value = "PY"});
            countries.Add(new NameValuePair {Name = "Peru", Value = "PE"});
            countries.Add(new NameValuePair {Name = "Philippines", Value = "PH"});
            countries.Add(new NameValuePair {Name = "Pitcairn", Value = "PN"});
            countries.Add(new NameValuePair {Name = "Poland", Value = "PL"});
            countries.Add(new NameValuePair {Name = "Portugal", Value = "PT"});
            countries.Add(new NameValuePair {Name = "Puerto Rico", Value = "PR"});
            countries.Add(new NameValuePair {Name = "Qatar", Value = "QA"});
            countries.Add(new NameValuePair {Name = "Reunion Réunion", Value = "RE"});
            countries.Add(new NameValuePair {Name = "Romania", Value = "RO"});
            countries.Add(new NameValuePair {Name = "Russian Federation", Value = "RU"});
            countries.Add(new NameValuePair {Name = "Rwanda", Value = "RW"});
            countries.Add(new NameValuePair {Name = "Saint Barthelemy Saint Barthélemy", Value = "BL"});
            countries.Add(new NameValuePair {Name = "Saint Helena", Value = "SH"});
            countries.Add(new NameValuePair {Name = "Saint Kitts and Nevis", Value = "KN"});
            countries.Add(new NameValuePair {Name = "Saint Lucia", Value = "LC"});
            countries.Add(new NameValuePair {Name = "Saint Martin (French part)", Value = "MF"});
            countries.Add(new NameValuePair {Name = "Saint Pierre and Miquelon", Value = "PM"});
            countries.Add(new NameValuePair {Name = "Saint Vincent and the Grenadines", Value = "VC"});
            countries.Add(new NameValuePair {Name = "Samoa", Value = "WS"});
            countries.Add(new NameValuePair {Name = "San Marino", Value = "SM"});
            countries.Add(new NameValuePair {Name = "Sao Tome and Principe", Value = "ST"});
            countries.Add(new NameValuePair {Name = "Saudi Arabia", Value = "SA"});
            countries.Add(new NameValuePair {Name = "Senegal", Value = "SN"});
            countries.Add(new NameValuePair {Name = "Serbia", Value = "RS"});
            countries.Add(new NameValuePair {Name = "Seychelles", Value = "SC"});
            countries.Add(new NameValuePair {Name = "Sierra Leone", Value = "SL"});
            countries.Add(new NameValuePair {Name = "Singapore", Value = "SG"});
            countries.Add(new NameValuePair {Name = "Slovakia", Value = "SK"});
            countries.Add(new NameValuePair {Name = "Slovenia", Value = "SI"});
            countries.Add(new NameValuePair {Name = "Solomon Islands", Value = "SB"});
            countries.Add(new NameValuePair {Name = "Somalia", Value = "SO"});
            countries.Add(new NameValuePair {Name = "South Africa", Value = "ZA"});
            countries.Add(new NameValuePair {Name = "South Georgia and the South Sandwich Islands", Value = "GS"});
            countries.Add(new NameValuePair {Name = "Spain", Value = "ES"});
            countries.Add(new NameValuePair {Name = "Sri Lanka", Value = "LK"});
            countries.Add(new NameValuePair {Name = "Sudan", Value = "SD"});
            countries.Add(new NameValuePair {Name = "Suriname", Value = "SR"});
            countries.Add(new NameValuePair {Name = "Svalbard and Jan Mayen", Value = "SJ"});
            countries.Add(new NameValuePair {Name = "Swaziland", Value = "SZ"});
            countries.Add(new NameValuePair {Name = "Sweden", Value = "SE"});
            countries.Add(new NameValuePair {Name = "Switzerland", Value = "CH"});
            countries.Add(new NameValuePair {Name = "Syrian Arab Republic", Value = "SY"});
            countries.Add(new NameValuePair {Name = "Taiwan, Province of China", Value = "TW"});
            countries.Add(new NameValuePair {Name = "Tajikistan", Value = "TJ"});
            countries.Add(new NameValuePair {Name = "Tanzania, United Republic of", Value = "TZ"});
            countries.Add(new NameValuePair {Name = "Thailand", Value = "TH"});
            countries.Add(new NameValuePair {Name = "Timor-Leste", Value = "TL"});
            countries.Add(new NameValuePair {Name = "Togo", Value = "TG"});
            countries.Add(new NameValuePair {Name = "Tokelau", Value = "TK"});
            countries.Add(new NameValuePair {Name = "Tonga", Value = "TO"});
            countries.Add(new NameValuePair {Name = "Trinidad and Tobago", Value = "TT"});
            countries.Add(new NameValuePair {Name = "Tunisia", Value = "TN"});
            countries.Add(new NameValuePair {Name = "Turkey", Value = "TR"});
            countries.Add(new NameValuePair {Name = "Turkmenistan", Value = "TM"});
            countries.Add(new NameValuePair {Name = "Turks and Caicos Islands", Value = "TC"});
            countries.Add(new NameValuePair {Name = "Tuvalu", Value = "TV"});
            countries.Add(new NameValuePair {Name = "Uganda", Value = "UG"});
            countries.Add(new NameValuePair {Name = "Ukraine", Value = "UA"});
            countries.Add(new NameValuePair {Name = "United Arab Emirates", Value = "AE"});
            countries.Add(new NameValuePair {Name = "United Kingdom", Value = "GB"});
            countries.Add(new NameValuePair {Name = "United States Minor Outlying Islands", Value = "UM"});
            countries.Add(new NameValuePair {Name = "United States", Value = "US"});
            countries.Add(new NameValuePair {Name = "Uruguay", Value = "UY"});
            countries.Add(new NameValuePair {Name = "Uzbekistan", Value = "UZ"});
            countries.Add(new NameValuePair {Name = "Vanuatu", Value = "VU"});
            countries.Add(new NameValuePair {Name = "Venezuela", Value = "VE"});
            countries.Add(new NameValuePair {Name = "Viet Nam", Value = "VN"});
            countries.Add(new NameValuePair {Name = "Virgin Islands, British", Value = "VG"});
            countries.Add(new NameValuePair {Name = "Virgin Islands, U.S.", Value = "VI"});
            countries.Add(new NameValuePair {Name = "Wallis and Futuna", Value = "WF"});
            countries.Add(new NameValuePair {Name = "Western Sahara", Value = "EH"});
            countries.Add(new NameValuePair {Name = "Yemen", Value = "YE"});
            countries.Add(new NameValuePair {Name = "Zambia", Value = "ZM"});
            countries.Add(new NameValuePair {Name = "Zimbabwe", Value = "ZW"});
            return countries;
        }

    }
    public struct NameValuePair
    {
        public string Name;
        public string Value;
    }
}